name: 'Publish Release Candidate'

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/package.json'
      - '.yarn/versions/**'

jobs:
  publish-rc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set node version
        id: node_version
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      - uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.node_version.outputs.NVMRC }}'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies and publish
        run: yarn && yarn publish:next
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit release candidate
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Publish release candidate'
